monthly/oct-2024/RacingRules/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace RacingRules.Controllers;

public class ErrorController : Controller
{
    [IgnoreAntiforgeryToken]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Index()
    {
        var exceptionHandler = HttpContext.Features.Get<IExceptionHandlerPathFeature>();
        return exceptionHandler?.Error is NullReferenceException
            ? View(new Views.Error.Index("ssm{race_c0nd1tions_are_fa1lure}"))
            : View(new Views.Error.Index(null));
    }
}

monthly/oct-2024/RacingRules/Controllers/RacingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using RacingRules.Services;
using RacingRules.Views.Racing;

namespace RacingRules.Controllers;

public class RacingController : Controller
{
    private readonly IMemoryCache _cache;

    public RacingController(IMemoryCache cache)
    {
        _cache = cache;
    }

    public IActionResult Index()
    {
        var participants = GetParticipant();

        Views.Racing.Index model = new(participants.Participants);
        return View(model);
    }

    [HttpPost]
    public IActionResult AddParticipant([FromForm] string firstName, [FromForm] string lastName)
    {
        var participants = GetParticipant();
        participants.Participants.Add(new Participant(firstName, lastName));

        return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult StartRace()
    {
        var participants = GetParticipant();

        List<LeaderboardEntry> unorderedEntries = [];
        Random random = new();
        foreach (var participant in participants.Participants)
        {
            unorderedEntries.Add(
                new LeaderboardEntry(
                    participant.FirstName,
                    participant.LastName,
                    timeForCompletion: TimeSpan.FromSeconds(random.Next(10, 100))
                )
            );
        }

        // Ordering from completion time
        participants.Leaderboard = unorderedEntries
            .OrderBy(l => l.TimeForCompletion.TotalSeconds)
            .ToList();

        // Disallow adding participants
        participants.Participants = null!;
        // Simulate racing
        _ = Task.Run(async () =>
        {
            await Task.Delay(TimeSpan.FromSeconds(5));
            // Allow adding participants
            participants.Participants = [];
        });
        return View();
    }

    public IActionResult Leaderboard()
    {
        var participants = GetParticipant();

        return View(new Leaderboard(participants.Leaderboard));
    }

    [HttpGet("/")]
    public IActionResult Main()
    {
        return Redirect("/Racing");
    }

    private ParticipantsService GetParticipant()
    {
        var address = HttpContext.Connection.RemoteIpAddress ?? HttpContext.Connection.LocalIpAddress;
        if (address is null)
        {
            throw new ArgumentException("Couldn't get users IP address");
        }

        ParticipantsService participants;
        if (_cache.TryGetValue(address, out var value))
        {
            participants = (value as ParticipantsService)!;
        }
        else
        {
            participants = new ParticipantsService();
            _cache.Set(address, participants, TimeSpan.FromMinutes(2));
        }

        return participants;
    }
}

monthly/oct-2024/RacingRules/Views/Racing/Index.cshtml
@model RacingRules.Views.Racing.Index

@{
    Layout = null;
    ViewBag.Title = "Racing participants";
}

<title>Racing participants</title>

<h1>Racing competition</h1>

<h2>Race conditions</h2>
<ol>
    <li>You don't talk about the race</li>
    <li>You don't talk about the race</li>
    <li>If a race is already on going. Use the emergency key</li>
    <li>Be nice, don't hurt anyone</li>
</ol>

<h2>Racing participants</h2>
@if (Model.Participants?.Count != 0)
{
    <ul>
        @foreach (var participant in Model.Participants ?? [])
        {
            <li>@participant.FirstName @participant.LastName</li>
        }
    </ul>
}
else
{
    <p>There is no participants!</p>
}

@using (Html.BeginForm("AddParticipant", "Racing"))
{
    <input type="text" placeholder="First name" name="firstName"/>
    <input type="text" placeholder="Last name" name="lastName"/>
    <button type="submit">Add participant</button>
}

@using (Html.BeginForm("StartRace", "Racing"))
{
    <button type="submit">Start race!</button>
}

monthly/oct-2024/RacingRules/Views/Racing/Leaderboard.cshtml
@model RacingRules.Views.Racing.Leaderboard

@{
    Layout = null;
}

<!DOCTYPE html>
<a herf="/Racing">Go back</a>
@if (Model.LeaderboardEntries is null)
{
    <p>There is no leaderboard entries</p>
}
else
{
    <ol>
        @foreach (var entry in Model.LeaderboardEntries)
        {
            <li>
                @entry.FirstName @entry.LastName - Completion: @(entry.TimeForCompletion.TotalSeconds)s
            </li>
        }
    </ol>
}

monthly/oct-2024/RacingRules/Views/Racing/StartRace.cshtml
<title>Starting race...</title>

<p>Racing...</p>
<p>Wait 5 seconds</p>
<script>
    setTimeout(() => {
        window.location.replace("/Racing/Leaderboard/");
    }, 5000);
</script>